Feature/api 22 command set
tremby/py-lightpack pull request #11
Opened 2019-02-03 16:47 UTC by renemarc

Solution for #6

2019-02-12 06:19 UTC, tremby requested changes

2019-02-12 06:19 UTC, tremby commented on lightpack.py
> +VERSION = '2.1.0'
The version number is dropping here.

2019-02-12 06:19 UTC, tremby commented on lightpack.py
> +class CommandDeprecatedError(RuntimeError):
Space between classes

2019-02-17 22:19 UTC, renemarc commented on lightpack.py
> +class CommandDeprecatedError(RuntimeError):
Fixed!

2019-02-17 22:20 UTC, renemarc commented
Rebased on **feature/api-15-command-set** to minimize merge conflicts.

2019-02-18 23:05 UTC, tremby commented on README.md
>  print("Locked:           %s" % lp.getLockStatus())
There's a rebase mistake here, which you fixed later. I'm going to tidy up a little and merge.

2019-02-18 23:29 UTC, tremby commented
I've manually merged and rebased these changes. Thanks very much!

2019-02-18 23:29 UTC, closed without merging